#!/bin/sh

# Convenience script to configure, build and install skycat in the given prefix dir.

# Edit the next line:
#prefix=/usr/local
prefix=$HOME/Software/skycat

make -f Makefile.in autoconf
./configure --with-tcl=$prefix/lib --with-tk=$prefix/lib --prefix=$prefix --exec_prefix=$prefix
make all install
#make release
